import test from 'node:test';
import assert from 'node:assert/strict';
import { distance,coordinates,arrival,validateFix,validatePhoto,nearbyPlaces,buildQuest,rewards,emptyStats,progression,weekKey,voiceCommand,alias,DEMO_ORIGIN,DEMO_PLACES } from '../web/lib/domain.js';
const now=Date.UTC(2026,9,8,9,0);
test('Geodesic distance and coordinate validation',()=>{assert.equal(distance(DEMO_ORIGIN,DEMO_ORIGIN),0);assert.ok(distance({lat:0,lon:0},{lat:0,lon:1})>111000);for(const bad of [{lat:91,lon:0},{lat:0,lon:Infinity},{lat:'1',lon:0},null])assert.throws(()=>coordinates(bad));});
test('GPS arrival rejects stale, inaccurate, and out-of-range check-ins',()=>{const p=DEMO_ORIGIN;assert.equal(arrival(p,{...p,accuracy:10,timestamp:now},now).arrived,true);assert.equal(arrival(p,{lat:p.lat+.01,lon:p.lon,accuracy:5,timestamp:now},now).arrived,false);assert.throws(()=>validateFix({...p,accuracy:66,timestamp:now},now));assert.throws(()=>validateFix({...p,accuracy:5,timestamp:now-31000},now));});
test('Camera metadata must describe a fresh, sufficiently sized image',()=>{const valid={hash:'a'.repeat(64),capturedAt:now,width:640,height:480};assert.equal(validatePhoto(valid,now-1000,now).width,640);for(const bad of [{...valid,capturedAt:now-400000},{...valid,capturedAt:now-2000},{...valid,hash:'bad'},{...valid,width:100},{...valid,width:undefined}])assert.throws(()=>validatePhoto(bad,now-1000,now));});
test('OSM grounding filters private and indoor places and uses nearest way geometry',()=>{const elements=[{type:'node',id:1,...DEMO_ORIGIN,tags:{leisure:'park',name:'Open Park'}},{type:'node',id:2,...DEMO_ORIGIN,tags:{leisure:'garden',access:'private'}},{type:'node',id:3,...DEMO_ORIGIN,tags:{tourism:'artwork',indoor:'yes'}},{type:'way',id:4,center:{lat:20,lon:20},geometry:[{lat:27.7175,lon:85.3242},{lat:27.718,lon:85.325}],tags:{leisure:'park',name:'Boundary Park'}},{type:'node',id:5,lat:25,lon:80,tags:{leisure:'park'}}];const p=nearbyPlaces(elements,DEMO_ORIGIN,500);assert.equal(p.length,2);assert.equal(p[1].lat,27.7175);assert.equal(p[0].source,'https://www.openstreetmap.org/node/1');});
test('Quests pin mapped coordinates and deterministic rewards independently of AI',()=>{const q=buildQuest({id:'q',places:DEMO_PLACES,type:'trail',theme:'astral',minutes:20,origin:DEMO_ORIGIN,narrative:{text:'A quiet magical grove.',model:'Gemma',runtime:'wasm'},now});assert.equal(q.checkpoints.length,3);assert.equal(q.xp,250);assert.equal(q.checkpoints[0].lat,DEMO_PLACES[0].lat);assert.equal(q.ai.model,'Gemma');assert.throws(()=>buildQuest({places:DEMO_PLACES.slice(0,1),type:'trail',minutes:20,origin:DEMO_ORIGIN}));});
test('Progression unlocks companions and trophies without streak penalties',()=>{let st=emptyStats();for(let i=0;i<25;i++)st=rewards(st,{type:i%3===0?'discover':'gate'},now+i*86400000).stats;assert.equal(st.quests,25);assert.equal(st.companions.length,6);assert.ok(st.trophies.includes('first'));assert.ok(st.trophies.includes('observer'));assert.ok(st.trophies.includes('steady'));assert.equal(progression(12000).rank.name,'S');assert.equal(progression(500).rank.name,'D');});
test('Weekly scores reset while permanent XP stays intact',()=>{let st=emptyStats();st=rewards(st,{type:'gate'},now).stats;st=rewards(st,{type:'gate'},now+7*86400000).stats;assert.equal(st.xp,200);assert.equal(st.weekXp,100);assert.notEqual(weekKey(now),weekKey(now+7*86400000));});
test('Voice command parsing and alias validation',()=>{assert.equal(voiceCommand('Repeat briefing'),'repeat');assert.equal(voiceCommand('check in'),'checkin');assert.equal(voiceCommand('resume quest'),'resume');assert.equal(voiceCommand('hello'),null);assert.equal(alias('Rohan_1'),'Rohan_1');assert.throws(()=>alias('<script>alert(1)</script>'));});
import {normalizeStory,discoveryFocus} from '../web/lib/domain.js';
test('Generated stories stay concise and discovery focuses come from allowed categories',()=>{assert.equal(normalizeStory('Leaves glow. A fox waits. A third sentence.'),'Leaves glow. A fox waits.');assert.equal(normalizeStory('You must defeat the rival factions.'),null);assert.equal(normalizeStory('```python\nprint(1)\n```'),null);assert.equal(discoveryFocus('Whispering leaves glow.','park'),'leaf shapes');assert.equal(discoveryFocus('Whispering leaves glow.','artwork'),'a shape or texture');});

